minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true
packages: []

allowBuilds:
  simple-git-hooks: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
